name: Deploy Lambda Function

on:
  push:
    branches: 
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Create Zip file for Lambda function
      - name: Create Zip file for Lambda function
        run: zip -r code.zip .

      # Step 3: Update the Lambda function using AWS CLI
      - name: Update Lambda Function
        uses: imehedi/actions-awscli-v2@latest
        with:
          args: |
            lambda update-function-code \
            --function-name arn:aws:lambda:us-east-2:211125585867:function:TestFunction \
            --zip-file fileb://code.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-2
